INSERT INTO artista(nome) VALUES ('10cc') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('A Flock of Seagulls') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('ABBA') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Al Green') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Alicia Keys') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Alphaville') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Ambrosia') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('America') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Australian Crawl') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Barry White') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Bee Gees') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Berlin') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Billy Idol') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Bob Marley & The Wailers') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Bobby Caldwell') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Bon Jovi') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Bonnie Tyler') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Brian Eno, John Cale') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Candi Staton') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Charles & Eddie') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Cheryl Lynn') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Crowded House') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Curtis Mayfield') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Cutting Crew') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Daryl Hall & John Oates') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('DeBarge') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Desireless') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Dire Straits') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Djo') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Eagles') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Earth, Wind & Fire') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Ed Motta') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Elton John') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Evelyn Champagne King') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Fallon Jennings') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Father John Misty') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Flashlight') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Fleetwood Mac') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Frank Jade') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('George Michael') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Gilbert O''Sullivan') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Innovations') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Jeff Buckley') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Jon Bon Jovi') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Journey') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Kool & The Gang') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Legião Urbana') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Lenny Kravitz') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('MFSB') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Madonna') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Marvin Gaye') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Matthew Wilder') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Men At Work') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Mica Paris') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Milton Wright') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Naked Eyes') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Natasha Bedingfield') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Neil Sedaka') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Neil Young') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('New Radicals') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Pearl Jam') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Pet Shop Boys') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Phil Collins') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Philip Bailey, Phil Collins') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Player') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Queen') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Regina Belle') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Scorpions') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Semisonic') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Sister Sledge') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Spandau Ballet') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Stevie Nicks') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Supertramp') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Tears for Fears') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('The Alan Parsons Project') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('The Blackbyrds') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('The Cars') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('The Colourfield') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('The Cure') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('The Doobie Brothers') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('The Doors') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('The Handsome Family') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('The Isley Brothers') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('The Nu-Luvs') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('The Police') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('The Rolling Stones') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('The Ronettes') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('The Smiths') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('The Three Degrees') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Three Dog Night') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Todd Rundgren') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Tom Petty') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Wham!') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('When In Rome') ON CONFLICT (nome) DO NOTHING;
INSERT INTO artista(nome) VALUES ('Teena Marie') ON CONFLICT (nome) DO NOTHING;

INSERT INTO musica(titulo, genero, artista_id) VALUES ('Eyes Without a Face', 'anos80', (SELECT id FROM artista WHERE nome = 'Billy Idol')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Everything She Wants', 'anos80', (SELECT id FROM artista WHERE nome = 'Wham!')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Eye in the Sky', 'anos80', (SELECT id FROM artista WHERE nome = 'The Alan Parsons Project')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Baby Come Back', 'anos70', (SELECT id FROM artista WHERE nome = 'Player')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Let''s Stay Together', 'anos70', (SELECT id FROM artista WHERE nome = 'Al Green')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('I''m Not In Love', 'anos70', (SELECT id FROM artista WHERE nome = '10cc')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('I Want You (Vocal)', 'anos70', (SELECT id FROM artista WHERE nome = 'Marvin Gaye')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Mercy Mercy Me (The Ecology)', 'anos70', (SELECT id FROM artista WHERE nome = 'Marvin Gaye')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Too Much Heaven', 'anos70', (SELECT id FROM artista WHERE nome = 'Bee Gees')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Night Fever (From "Saturday Night Fever" Soundtrack)', 'anos70', (SELECT id FROM artista WHERE nome = 'Bee Gees')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('How Deep Is Your Love (From "Saturday Night Fever" Soundtrack)', 'anos70', (SELECT id FROM artista WHERE nome = 'Bee Gees')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Drive', 'anos80', (SELECT id FROM artista WHERE nome = 'The Cars')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Who Can It Be Now?', 'anos80', (SELECT id FROM artista WHERE nome = 'Men At Work')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Last Christmas', 'anos80', (SELECT id FROM artista WHERE nome = 'Wham!')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Careless Whisper', 'anos80', (SELECT id FROM artista WHERE nome = 'George Michael')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Promises, Promises (Us Single Version)', 'anos80', (SELECT id FROM artista WHERE nome = 'Naked Eyes')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('It''s a Mistake', 'anos80', (SELECT id FROM artista WHERE nome = 'Men At Work')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Dreams', 'anos70', (SELECT id FROM artista WHERE nome = 'Fleetwood Mac')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Real Love Baby', 'anos2010', (SELECT id FROM artista WHERE nome = 'Father John Misty')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Could You Be Loved', 'anos80', (SELECT id FROM artista WHERE nome = 'Bob Marley & The Wailers')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Unpublished Critics (2013 Remaster)', 'anos80', (SELECT id FROM artista WHERE nome = 'Australian Crawl')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('The Boys Are Back In Town', 'anos80', (SELECT id FROM artista WHERE nome = 'Bon Jovi')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Wrapped Around Your Finger (Remastered 2003)', 'anos80', (SELECT id FROM artista WHERE nome = 'The Police')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('How Much I Feel', 'anos70', (SELECT id FROM artista WHERE nome = 'Ambrosia')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('It Only Hurts When I Breathe', 'anos70', (SELECT id FROM artista WHERE nome = 'Player')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Lover, You Should''ve Come Over', 'anos90', (SELECT id FROM artista WHERE nome = 'Jeff Buckley')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('I Ran (So Far Away)', 'anos80', (SELECT id FROM artista WHERE nome = 'A Flock of Seagulls')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('You Get What You Give', 'anos90', (SELECT id FROM artista WHERE nome = 'New Radicals')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Love Is a Long Road', 'anos80', (SELECT id FROM artista WHERE nome = 'Tom Petty')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Young Hearts Run Free', 'anos70', (SELECT id FROM artista WHERE nome = 'Candi Staton')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Rocket Man (I Think It''s Going to Be a Long Long Time)', 'anos70', (SELECT id FROM artista WHERE nome = 'Elton John')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Head Over Heels', 'anos80', (SELECT id FROM artista WHERE nome = 'Tears for Fears')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('If You Were There', 'anos80', (SELECT id FROM artista WHERE nome = 'Wham!')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Break My Stride', 'anos80', (SELECT id FROM artista WHERE nome = 'Matthew Wilder')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Boys Don''t Cry', 'anos80', (SELECT id FROM artista WHERE nome = 'The Cure')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('You Might Think', 'anos80', (SELECT id FROM artista WHERE nome = 'The Cars')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('I''m Still Standing', 'anos80', (SELECT id FROM artista WHERE nome = 'Elton John')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Big In Japan', 'anos80', (SELECT id FROM artista WHERE nome = 'Alphaville')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Angel Eyes', 'anos70', (SELECT id FROM artista WHERE nome = 'ABBA')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('In Between Days', 'anos80', (SELECT id FROM artista WHERE nome = 'The Cure')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Easy Lover', 'anos80', (SELECT id FROM artista WHERE nome = 'Philip Bailey, Phil Collins')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('This Charming Man', 'anos80', (SELECT id FROM artista WHERE nome = 'The Smiths')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Upstairs In My House', 'anos80', (SELECT id FROM artista WHERE nome = 'Men At Work')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('It Ain''t Over ''Til It''s Over', 'anos90', (SELECT id FROM artista WHERE nome = 'Lenny Kravitz')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('I Don''t Wanna Know (2016 Remastered)', 'anos80', (SELECT id FROM artista WHERE nome = 'Phil Collins')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('How Can You Mend a Broken Heart', 'anos70', (SELECT id FROM artista WHERE nome = 'Al Green')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Dreaming About You', 'anos70', (SELECT id FROM artista WHERE nome = 'The Blackbyrds')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Soldier of Love', 'anos2000', (SELECT id FROM artista WHERE nome = 'Pearl Jam')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('T.S.O.P. (The Sound of Philadelphia) [feat. The Three Degrees]', 'anos70', (SELECT id FROM artista WHERE nome = 'MFSB')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('September', 'anos70', (SELECT id FROM artista WHERE nome = 'Earth, Wind & Fire')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Holding Out for a Hero', 'anos80', (SELECT id FROM artista WHERE nome = 'Bonnie Tyler')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Take My Breath Away (Love Theme from "Top Gun")', 'anos80', (SELECT id FROM artista WHERE nome = 'Berlin')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Alone Again (Naturally)', 'anos70', (SELECT id FROM artista WHERE nome = 'Gilbert O''Sullivan')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('What You Won''t Do for Love', 'anos70', (SELECT id FROM artista WHERE nome = 'Bobby Caldwell')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Seabird', 'anos70', (SELECT id FROM artista WHERE nome = 'Innovations')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Unwritten', 'anos2000', (SELECT id FROM artista WHERE nome = 'Natasha Bedingfield')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('My Kind of Lady', 'anos80', (SELECT id FROM artista WHERE nome = 'Supertramp')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('West End Girls', 'anos80', (SELECT id FROM artista WHERE nome = 'Pet Shop Boys')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Love Is the Message', 'anos70', (SELECT id FROM artista WHERE nome = 'MFSB')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Tempo Perdido', 'anos80', (SELECT id FROM artista WHERE nome = 'Legião Urbana')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Never, Never Gonna Give Ya Up', 'anos70', (SELECT id FROM artista WHERE nome = 'Barry White')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Still Not Satisfied', 'anos80', (SELECT id FROM artista WHERE nome = 'Ambrosia')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Biggest Part of Me', 'anos80', (SELECT id FROM artista WHERE nome = 'Ambrosia')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Como Dois Cristais / Música Incidental: Jah Dread', 'anos90', (SELECT id FROM artista WHERE nome = 'Ed Motta')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('You Don''t Know My Name', 'anos2000', (SELECT id FROM artista WHERE nome = 'Alicia Keys')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('End of Beginning', 'anos2020', (SELECT id FROM artista WHERE nome = 'Djo')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Edge of Seventeen', 'anos80', (SELECT id FROM artista WHERE nome = 'Stevie Nicks')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('You Make My Dreams', 'anos80', (SELECT id FROM artista WHERE nome = 'Daryl Hall & John Oates')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Ooo La La La (12-inch version)', 'anos80', (SELECT id FROM artista WHERE nome = 'Teena Marie')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('The Silence That You Keep', 'anos70', (SELECT id FROM artista WHERE nome = 'Milton Wright')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('The Promise', 'anos80', (SELECT id FROM artista WHERE nome = 'When In Rome')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Voyage voyage', 'anos80', (SELECT id FROM artista WHERE nome = 'Desireless')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Sultans Of Swing', 'anos70', (SELECT id FROM artista WHERE nome = 'Dire Straits')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Take A Chance On Me', 'anos70', (SELECT id FROM artista WHERE nome = 'ABBA')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('I Don''t Know If It''s Right', 'anos70', (SELECT id FROM artista WHERE nome = 'Evelyn Champagne King')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Who''s Crying Now', 'anos80', (SELECT id FROM artista WHERE nome = 'Journey')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Summer Love', 'anos70', (SELECT id FROM artista WHERE nome = 'The Blackbyrds')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Can''t Get Enough of You Baby', 'anos80', (SELECT id FROM artista WHERE nome = 'The Colourfield')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('F.N.T.', 'anos90', (SELECT id FROM artista WHERE nome = 'Semisonic')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Downhearted (Remastered)', 'anos80', (SELECT id FROM artista WHERE nome = 'Australian Crawl')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('When Will I See You Again', 'anos70', (SELECT id FROM artista WHERE nome = 'The Three Degrees')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Someday We''ll Know', 'anos90', (SELECT id FROM artista WHERE nome = 'New Radicals')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Heavy Love Affair', 'anos80', (SELECT id FROM artista WHERE nome = 'Marvin Gaye')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('A Horse With No Name', 'anos70', (SELECT id FROM artista WHERE nome = 'America')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('I Saw the Light', 'anos70', (SELECT id FROM artista WHERE nome = 'Todd Rundgren')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Spinning Away', 'anos90', (SELECT id FROM artista WHERE nome = 'Brian Eno, John Cale')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Get Down On It', 'anos80', (SELECT id FROM artista WHERE nome = 'Kool & The Gang')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Thinking of You (1995 Remaster)', 'anos70', (SELECT id FROM artista WHERE nome = 'Sister Sledge')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Dancing Queen', 'anos70', (SELECT id FROM artista WHERE nome = 'ABBA')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Young Free and Single', 'anos80', (SELECT id FROM artista WHERE nome = 'Frank Jade')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Message In a Bottle', 'anos70', (SELECT id FROM artista WHERE nome = 'The Police')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Donkey Jaw', 'anos70', (SELECT id FROM artista WHERE nome = 'America')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Tragedy', 'anos70', (SELECT id FROM artista WHERE nome = 'Bee Gees')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('(I Just) Died in Your Arms', 'anos80', (SELECT id FROM artista WHERE nome = 'Cutting Crew')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Dream', 'anos70', (SELECT id FROM artista WHERE nome = 'Al Green')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Can''t Stand Losing You (Remastered 2003)', 'anos70', (SELECT id FROM artista WHERE nome = 'The Police')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Errol (Remastered)', 'anos80', (SELECT id FROM artista WHERE nome = 'Australian Crawl')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Harvest Moon', 'anos90', (SELECT id FROM artista WHERE nome = 'Neil Young')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('I Like It', 'anos80', (SELECT id FROM artista WHERE nome = 'DeBarge')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Don''t Dream It''s Over', 'anos80', (SELECT id FROM artista WHERE nome = 'Crowded House')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Blue Sunday', 'anos70', (SELECT id FROM artista WHERE nome = 'The Doors')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('All Night Long', 'anos80', (SELECT id FROM artista WHERE nome = 'Fallon Jennings')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('My One Temptation', 'anos80', (SELECT id FROM artista WHERE nome = 'Mica Paris')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Barbarism Begins at Home', 'anos80', (SELECT id FROM artista WHERE nome = 'The Smiths')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('What Goes Around Comes Around', 'anos90', (SELECT id FROM artista WHERE nome = 'Regina Belle')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Would I Lie To You?', 'anos90', (SELECT id FROM artista WHERE nome = 'Charles & Eddie')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Encore', 'anos80', (SELECT id FROM artista WHERE nome = 'Cheryl Lynn')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Distant Lover', 'anos70', (SELECT id FROM artista WHERE nome = 'Marvin Gaye')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Every Little Beat of My Heart', 'anos80', (SELECT id FROM artista WHERE nome = 'Flashlight')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Girl Afraid', 'anos80', (SELECT id FROM artista WHERE nome = 'The Smiths')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Footsteps In the Dark (Pt. 1 & 2)', 'anos70', (SELECT id FROM artista WHERE nome = 'The Isley Brothers')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('One of These Nights', 'anos70', (SELECT id FROM artista WHERE nome = 'Eagles')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Miracle', 'anos90', (SELECT id FROM artista WHERE nome = 'Jon Bon Jovi')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Easy to Be Hard (Single Version)', 'anos60', (SELECT id FROM artista WHERE nome = 'Three Dog Night')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Always Somewhere', 'anos70', (SELECT id FROM artista WHERE nome = 'Scorpions')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Far from Any Road', 'anos2000', (SELECT id FROM artista WHERE nome = 'The Handsome Family')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Bigmouth Strikes Again', 'anos80', (SELECT id FROM artista WHERE nome = 'The Smiths')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Laughter In The Rain', 'anos70', (SELECT id FROM artista WHERE nome = 'Neil Sedaka')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('The Makings of You', 'anos70', (SELECT id FROM artista WHERE nome = 'Curtis Mayfield')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Cool Cat', 'anos80', (SELECT id FROM artista WHERE nome = 'Queen')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('La Isla Bonita', 'anos80', (SELECT id FROM artista WHERE nome = 'Madonna')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('I Can''t Go for That (No Can Do)', 'anos80', (SELECT id FROM artista WHERE nome = 'Daryl Hall & John Oates')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Say You Love Me (Remastered)', 'anos70', (SELECT id FROM artista WHERE nome = 'Fleetwood Mac')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Wild Horses', 'anos70', (SELECT id FROM artista WHERE nome = 'The Rolling Stones')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('What a Fool Believes', 'anos70', (SELECT id FROM artista WHERE nome = 'The Doobie Brothers')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Ventura Highway', 'anos70', (SELECT id FROM artista WHERE nome = 'America')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Like a Prayer', 'anos80', (SELECT id FROM artista WHERE nome = 'Madonna')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Like a Virgin', 'anos80', (SELECT id FROM artista WHERE nome = 'Madonna')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Baby You Belong To Me', 'anos70', (SELECT id FROM artista WHERE nome = 'The Nu-Luvs')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('True', 'anos80', (SELECT id FROM artista WHERE nome = 'Spandau Ballet')) ON CONFLICT DO NOTHING;
INSERT INTO musica(titulo, genero, artista_id) VALUES ('Be My Baby', 'anos60', (SELECT id FROM artista WHERE nome = 'The Ronettes')) ON CONFLICT DO NOTHING;